### ISSUE TITLE
Call to undefined method App\Roles\UserMenuRole::dispatch() [Bug]: 

### ISSUE THREAD

**Issue by wisnubaldas** [binary-cats/laravel-rbac#11]
### What happened?

there was an error when executing the command `php artisan rbac:reset` 

### How to reproduce the bug

![gambar](https://github.com/user-attachments/assets/1cef60d7-6dfd-4a00-9895-fbc0f3538897)

UserMenuRole
![gambar](https://github.com/user-attachments/assets/91aa3260-c8fe-465a-947d-082a7b0a330c)

MenuAbility
![gambar](https://github.com/user-attachments/assets/1673f791-5b61-4500-a978-6a78f155548a)

### Package Version

1.1

### PHP Version

8.3.8

### Laravel Version

11.17.0

### Which operating systems does with happen with?

Windows

**Comment by cyrillkalita** [comment]
@wisnubaldas the role definition seems fine to me, but it looks like there are 4 jobs running from the config.
the package ships three, so my guess  you have added `UserMenuRole::class` to the `rbac.jobs` instead of `rbac.roles` config key

Can you take a look?

**Comment by wisnubaldas** [comment]
![gambar](https://github.com/user-attachments/assets/11d13d7f-1196-44fa-b463-c6cbe68b8bb9)

this is my rbac.php configuration, but I still get the error

**Comment by cyrillkalita** [comment]
Yes, that's what I mean.
Place your role in the 'roles' array

**Comment by wisnubaldas** [comment]
![gambar](https://github.com/user-attachments/assets/a5f32dad-fc4c-4def-95b2-2c79b7068323)

like this

![gambar](https://github.com/user-attachments/assets/7d23f6ca-70e8-4fad-bfc8-2cd93d85bad0)
